### ISSUE TITLE
Rename to `eth2-networks`

### ISSUE THREAD

**Issue by arnetheduck** [eth2-clients/eth2-networks#46]
We have two repos keeping track of known eth2 networks - this one and https://github.com/eth2-clients/eth2-mainnet - life can be made easier by simply renaming this one to `eth2-networks` and deprecating `eth2-mainnet` - conveniently, the mainnet data is already in this repo and more recent than the `eth2-mainnet` data (https://github.com/eth2-clients/eth2-mainnet/pull/5)

**Comment by arnetheduck** [comment]
From a practical pov, the transition is simplified by github putting in place a redirect from the old name, so existing links won't break.

**Comment by ajsutton** [comment]
Sounds good to me.

**Comment by protolambda** [comment]
Sounds good

**Comment by terencechain** [comment]
sounds good
